//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/QRCode/Framework/UI/InputIcon/Inputs/Inputs_Tests.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs_Tests : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs_Tests()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs_Tests"",
    ""maps"": [
        {
            ""name"": ""Tests"",
            ""id"": ""ae91eb92-99ac-4623-b508-7bd60c494102"",
            ""actions"": [
                {
                    ""name"": ""Validate"",
                    ""type"": ""Button"",
                    ""id"": ""0372df8d-bab7-4145-bbec-e8dbe2f61874"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b758fe68-3b7b-442e-a869-9c66330a51bd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Validate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5a2c1b3-9de8-4c25-a65e-7edb4c5d5fc2"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Validate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Xbox Controller"",
            ""bindingGroup"": ""Xbox Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Tests
        m_Tests = asset.FindActionMap("Tests", throwIfNotFound: true);
        m_Tests_Validate = m_Tests.FindAction("Validate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Tests
    private readonly InputActionMap m_Tests;
    private ITestsActions m_TestsActionsCallbackInterface;
    private readonly InputAction m_Tests_Validate;
    public struct TestsActions
    {
        private @Inputs_Tests m_Wrapper;
        public TestsActions(@Inputs_Tests wrapper) { m_Wrapper = wrapper; }
        public InputAction @Validate => m_Wrapper.m_Tests_Validate;
        public InputActionMap Get() { return m_Wrapper.m_Tests; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TestsActions set) { return set.Get(); }
        public void SetCallbacks(ITestsActions instance)
        {
            if (m_Wrapper.m_TestsActionsCallbackInterface != null)
            {
                @Validate.started -= m_Wrapper.m_TestsActionsCallbackInterface.OnValidate;
                @Validate.performed -= m_Wrapper.m_TestsActionsCallbackInterface.OnValidate;
                @Validate.canceled -= m_Wrapper.m_TestsActionsCallbackInterface.OnValidate;
            }
            m_Wrapper.m_TestsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Validate.started += instance.OnValidate;
                @Validate.performed += instance.OnValidate;
                @Validate.canceled += instance.OnValidate;
            }
        }
    }
    public TestsActions @Tests => new TestsActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_XboxControllerSchemeIndex = -1;
    public InputControlScheme XboxControllerScheme
    {
        get
        {
            if (m_XboxControllerSchemeIndex == -1) m_XboxControllerSchemeIndex = asset.FindControlSchemeIndex("Xbox Controller");
            return asset.controlSchemes[m_XboxControllerSchemeIndex];
        }
    }
    public interface ITestsActions
    {
        void OnValidate(InputAction.CallbackContext context);
    }
}
