//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/QRCode/Framework/UI/InputIcon/Inputs/Inputs_Tests.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs_Tests : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs_Tests()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs_Tests"",
    ""maps"": [
        {
            ""name"": ""Tests"",
            ""id"": ""ae91eb92-99ac-4623-b508-7bd60c494102"",
            ""actions"": [
                {
                    ""name"": ""PrimaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""0372df8d-bab7-4145-bbec-e8dbe2f61874"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""44844788-740c-4563-ba61-0de7f57d9ad2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d1d23a5e-8ddd-4888-b96d-42d7b13b18b4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""569639e3-c143-43a1-8675-e3576aaaf935"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestInpuDisplayName"",
                    ""type"": ""Button"",
                    ""id"": ""7c29cdac-da29-4b36-ac61-57374532a6d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b758fe68-3b7b-442e-a869-9c66330a51bd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""PrimaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5a2c1b3-9de8-4c25-a65e-7edb4c5d5fc2"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""PrimaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9407acdc-78c9-429f-a4a4-d08036c8c40a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SecondaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b520548e-ff26-4f68-8ca2-f0c0d830e49a"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""SecondaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""319d7d5f-5a1e-45d9-8250-111443b7101a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""de12c740-fccb-4c74-a297-c2ffdb046575"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5cc973f0-c246-47e4-bf74-733cdac5b1c6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XboxController"",
                    ""id"": ""e77d377e-2a0b-40c9-b3c4-b7ca53815511"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f20bb555-3fb4-4a11-b146-a3691f0f9df2"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3e65e305-f2a8-4fd2-83aa-8e8f33230191"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ac44106a-3e2d-480b-9b2d-9052e77702e4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2ee4ff0-c282-43d9-87f1-f31e7822cfa0"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""160fcef0-e281-4e71-b89b-ec867adfd7f8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""TestInpuDisplayName"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ca98096-bc5f-4bb9-9d6b-454518edf820"",
                    ""path"": ""<XInputController>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""TestInpuDisplayName"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Xbox Controller"",
            ""bindingGroup"": ""Xbox Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Tests
        m_Tests = asset.FindActionMap("Tests", throwIfNotFound: true);
        m_Tests_PrimaryAction = m_Tests.FindAction("PrimaryAction", throwIfNotFound: true);
        m_Tests_SecondaryAction = m_Tests.FindAction("SecondaryAction", throwIfNotFound: true);
        m_Tests_Move = m_Tests.FindAction("Move", throwIfNotFound: true);
        m_Tests_MoveUp = m_Tests.FindAction("MoveUp", throwIfNotFound: true);
        m_Tests_TestInpuDisplayName = m_Tests.FindAction("TestInpuDisplayName", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Tests
    private readonly InputActionMap m_Tests;
    private ITestsActions m_TestsActionsCallbackInterface;
    private readonly InputAction m_Tests_PrimaryAction;
    private readonly InputAction m_Tests_SecondaryAction;
    private readonly InputAction m_Tests_Move;
    private readonly InputAction m_Tests_MoveUp;
    private readonly InputAction m_Tests_TestInpuDisplayName;
    public struct TestsActions
    {
        private @Inputs_Tests m_Wrapper;
        public TestsActions(@Inputs_Tests wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryAction => m_Wrapper.m_Tests_PrimaryAction;
        public InputAction @SecondaryAction => m_Wrapper.m_Tests_SecondaryAction;
        public InputAction @Move => m_Wrapper.m_Tests_Move;
        public InputAction @MoveUp => m_Wrapper.m_Tests_MoveUp;
        public InputAction @TestInpuDisplayName => m_Wrapper.m_Tests_TestInpuDisplayName;
        public InputActionMap Get() { return m_Wrapper.m_Tests; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TestsActions set) { return set.Get(); }
        public void SetCallbacks(ITestsActions instance)
        {
            if (m_Wrapper.m_TestsActionsCallbackInterface != null)
            {
                @PrimaryAction.started -= m_Wrapper.m_TestsActionsCallbackInterface.OnPrimaryAction;
                @PrimaryAction.performed -= m_Wrapper.m_TestsActionsCallbackInterface.OnPrimaryAction;
                @PrimaryAction.canceled -= m_Wrapper.m_TestsActionsCallbackInterface.OnPrimaryAction;
                @SecondaryAction.started -= m_Wrapper.m_TestsActionsCallbackInterface.OnSecondaryAction;
                @SecondaryAction.performed -= m_Wrapper.m_TestsActionsCallbackInterface.OnSecondaryAction;
                @SecondaryAction.canceled -= m_Wrapper.m_TestsActionsCallbackInterface.OnSecondaryAction;
                @Move.started -= m_Wrapper.m_TestsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_TestsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_TestsActionsCallbackInterface.OnMove;
                @MoveUp.started -= m_Wrapper.m_TestsActionsCallbackInterface.OnMoveUp;
                @MoveUp.performed -= m_Wrapper.m_TestsActionsCallbackInterface.OnMoveUp;
                @MoveUp.canceled -= m_Wrapper.m_TestsActionsCallbackInterface.OnMoveUp;
                @TestInpuDisplayName.started -= m_Wrapper.m_TestsActionsCallbackInterface.OnTestInpuDisplayName;
                @TestInpuDisplayName.performed -= m_Wrapper.m_TestsActionsCallbackInterface.OnTestInpuDisplayName;
                @TestInpuDisplayName.canceled -= m_Wrapper.m_TestsActionsCallbackInterface.OnTestInpuDisplayName;
            }
            m_Wrapper.m_TestsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PrimaryAction.started += instance.OnPrimaryAction;
                @PrimaryAction.performed += instance.OnPrimaryAction;
                @PrimaryAction.canceled += instance.OnPrimaryAction;
                @SecondaryAction.started += instance.OnSecondaryAction;
                @SecondaryAction.performed += instance.OnSecondaryAction;
                @SecondaryAction.canceled += instance.OnSecondaryAction;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @MoveUp.started += instance.OnMoveUp;
                @MoveUp.performed += instance.OnMoveUp;
                @MoveUp.canceled += instance.OnMoveUp;
                @TestInpuDisplayName.started += instance.OnTestInpuDisplayName;
                @TestInpuDisplayName.performed += instance.OnTestInpuDisplayName;
                @TestInpuDisplayName.canceled += instance.OnTestInpuDisplayName;
            }
        }
    }
    public TestsActions @Tests => new TestsActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_XboxControllerSchemeIndex = -1;
    public InputControlScheme XboxControllerScheme
    {
        get
        {
            if (m_XboxControllerSchemeIndex == -1) m_XboxControllerSchemeIndex = asset.FindControlSchemeIndex("Xbox Controller");
            return asset.controlSchemes[m_XboxControllerSchemeIndex];
        }
    }
    public interface ITestsActions
    {
        void OnPrimaryAction(InputAction.CallbackContext context);
        void OnSecondaryAction(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnMoveUp(InputAction.CallbackContext context);
        void OnTestInpuDisplayName(InputAction.CallbackContext context);
    }
}
